version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8983:8983"
    networks:
      - mynetwork

  standalone-chromium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
